apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    team: tech-and-product
    env: production
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
  nodeName: worker1