apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kc-volume-claim
  labels:
    app: kc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  selector:
    matchLabels:
      app: kc