apiVersion: v1
kind: PersistentVolume
metadata:
  name: kc-volume
  labels:
    app: kc
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: manual
  hostPath:
    path: /opt/volume/kc
