apiVersion: v1
kind: PersistentVolume
metadata:
  name: moodle-volume
  labels:
    app: moodle
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/volume/moodle