apiVersion: v1
kind: Service
metadata:
  name: moodle-service
  labels:
    app: moodle
spec:
  type: NodePort
  selector:
    app: moodle
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008