apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodle-volume-claim
  labels:
    app: moodle
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      app: moodle