apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
        - image: wordpress
          name: wordpress
          imagePullPolicy: IfNotPresent

          env:
            - name: WORDPRESS_DB_HOST
              value: wordpress-mysql

            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password

            - name: WORDPRESS_DB_USER
              value: mysql

            - name: WORDPRESS_DB_NAME
              value: mysql

          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
      nodeSelector:
        storage: local
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wp-volume-claim