apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
  selector:
    matchLabels:
      app: wordpress