kind: PersistentVolume
apiVersion: v1
metadata:
  name: wp-volume
  labels:
    app: wordpress
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/volume/wordpress"