apiVersion: v1
kind: Service
metadata:
  name: joomla-service
  labels:
    app: joomla
spec:
  selector:
    app: joomla
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009