apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: joomla-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: joomla